INSTALL_TARGET_PROCESSES = SpringBoard

include ~/theos/makefiles/common.mk

TWEAK_NAME = 1stDateLastTime

1stDateLastTime_FILES = Tweak.xm
1stDateLastTime_CFLAGS = -fobjc-arc

include ~/theos/makefiles/tweak.mk
